# Generated by Django 3.2.25 on 2024-08-18 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_rename_nombreresponsable_bodega_nombre_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
