# Generated by Django 3.2.25 on 2024-08-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedor_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha_ingreso',
        ),
    ]
