# Generated by Django 3.2.25 on 2024-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_proveedor_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='retirado',
            field=models.BooleanField(default=False),
        ),
    ]
