# Generated by Django 3.2.25 on 2024-08-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_proveedor_retirado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='apellido',
            field=models.CharField(default='Apellido por defecto', max_length=100),
        ),
    ]
