# Generated by Django 3.2.25 on 2024-09-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_proveedor_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.bodega'),
        ),
    ]
