# Generated by Django 3.2.25 on 2024-09-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0010_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fecha_retiro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
